name: Go CI/CD

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test ./...

  docker:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'  # chỉ chạy job này khi push lên main
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t duycutephomaique/go-app:latest .

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Build Docker image
        run: docker build -t duycutephomaique/go-app:latest .

      - name: Push Docker image
        run: docker push duycutephomaique/go-app:latest
