name: Go CI/CD

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test ./...

  docker:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main'  # chỉ chạy job này khi push lên main
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t duycutephomaique/go-app:latest .

      - name: Push Docker image
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push duycutephomaique/go-app:latest
