name: Go CI/CD

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
    tags:
      - '*'
  pull_request:
    branches:
      - main
      - develop
      - 'feature/*'

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test ./...

  docker:
    runs-on: ubuntu-latest
    needs: ci
    if: github.ref == 'refs/heads/main' || github.ref_type == 'tag'  # chỉ chạy job này khi push lên main
    environment: key docker
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Determine Docker Tag
        id: vars
        run: |
          if [[ "${GITHUB_REF_TYPE}" == "tag" ]]; then
            echo "TAG_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=latest" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        run: docker build -t duycutephomaique/go-app-auto-ci:${TAG_NAME} .

      - name: Push Docker image
        run: docker push duycutephomaique/go-app-auto-ci:${TAG_NAME}
